name: tests
on: push

env:
  golang-version: '1.16.13'
  go-cpro-version: 'v1.16.13-msspi'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          platform: win64
        - os: ubuntu-latest
          platform: linux
        - os: macos-latest
          platform: darwin

    name: TLS-Client
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.golang-version }}

    - name: Setup CryptoPro/go
      env:
        PROJECTTAG: ${{ env.go-cpro-version }}
      shell: bash
      run: |
        cd $RUNNER_TEMP
        git -c advice.detachedHead=false clone --depth 1 --branch ${PROJECTTAG} https://github.com/CryptoPro/go.git
        cd go
        git submodule update --init --recursive --depth 1
        cd src/go-msspi/msspi/build_linux
        make -B static
        if [ "$RUNNER_OS" != "Windows" ]; then
          make -B static-capix
        fi
        cp -rf $RUNNER_TEMP/go/src $GOROOT

    - name: Install CryptoPro CSP
      env:
        CPRO_CREDENTIALS: ${{ secrets.CPRO_CREDENTIALS }}
      shell: bash
      run: |
        cd $RUNNER_TEMP
        if [ "$RUNNER_OS" == "Windows" ]; then
          curl https://${CPRO_CREDENTIALS}@update.cryptopro.ru/support/stunnel/dist/csp50r2/csp-x64-eng.msi --output csp-x64-eng.msi
          start //wait msiexec //qn //i "csp-x64-eng.msi" REBOOT=R INSTALLCPCERT=1 KCLEVEL=1
        elif [ "$RUNNER_OS" == "Linux" ]; then
          curl https://${CPRO_CREDENTIALS}@update.cryptopro.ru/support/stunnel/dist/csp50r2/linux-amd64_deb.tgz --output linux-amd64_deb.tgz
          tar -xvf linux-amd64_deb.tgz
          cd linux-amd64_deb
          sudo ./install.sh kc1
        elif [ "$RUNNER_OS" == "macOS" ]; then
          curl https://${CPRO_CREDENTIALS}@update.cryptopro.ru/support/stunnel/dist/csp50r2/ru.cryptopro.csp.dmg --output ru.cryptopro.csp.dmg
          hdiutil attach ru.cryptopro.csp.dmg
          cd /Volumes/ru.cryptopro.csp*
          sudo installer -pkg ru.cryptopro.csp*.pkg -target /
        else
          exit 1
        fi

    - name: TLS-Client
      run: |
        go test -run MsspiClient
