name: test
on: [push]

env:
  golang-version: '1.16.5'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
        - os: macos-latest
          platform: darwin
        - os: windows-latest
          platform: win32

    name: TestMsspiClient
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.golang-version }}

    - name: Setup CryptoPro/go
      shell: bash
      run: |
        pwd
        cd $RUNNER_TEMP
        git clone --depth 1 --branch go.1.16-msspi https://github.com/CryptoPro/go.git
        cd go
        git submodule init
        git submodule update --depth 1
        export GOROOT=$RUNNER_TEMP/go
        go env

    - name: TestMsspiClient
      shell: bash
      run: |
        pwd
        cd $GITHUB_WORKSPACE
        go env
        go test -run MsspiClient
