name: test
on: [push]

env:
  golang-version: '1.16.5'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
        - os: windows-latest
          platform: win32

    name: TestMsspiClient
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.golang-version }}

    - name: Setup CryptoPro/go
      shell: bash
      run: |
        cd $RUNNER_TEMP
        git clone --depth 1 --branch go.1.16-msspi https://github.com/CryptoPro/go.git
        cd go
        git submodule update --init --recursive --depth 1
        cd src/go-msspi/msspi/build_linux
        make -B static
        if [ "$RUNNER_OS" != "Windows" ]; then
          make -B static-capix
          cp -rf $RUNNER_TEMP/go/src $GOROOT
        else
          cp -rf $RUNNER_TEMP\go\src $GOROOT
        fi

    - name: TestMsspiClient
      shell: bash
      run: |
        go test -run MsspiClient
