name: test
on: [push]

env:
  golang-version: '1.16.5'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          platform: win32
        - os: ubuntu-latest
          platform: linux

    name: TestMsspiClient
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.golang-version }}

    - name: Setup CryptoPro/go
      shell: bash
      run: |
        cd $RUNNER_TEMP
        git clone --depth 1 --branch go.1.16-msspi https://github.com/CryptoPro/go.git
        cd go
        git submodule update --init --recursive --depth 1
        cd src/go-msspi/msspi/build_linux
        make -B static
        if [ "$RUNNER_OS" != "Windows" ]; then
          make -B static-capix
        fi
        cp -rf $RUNNER_TEMP/go/src $GOROOT

    - name: Install CryptoPro CSP
      env:
        CPRO_CREDENTIALS: ${{ secrets.CPRO_CREDENTIALS }}
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          curl https://${CPRO_CREDENTIALS}@update.cryptopro.ru/support/stunnel/dist/csp50r2/CSPSetup.exe --output CSPSetup.exe
          CSPSetup.exe -lang eng -kc kc1 -silent -noreboot
        elif [ "$RUNNER_OS" == "Linux" ]; then
          curl https://${CPRO_CREDENTIALS}@update.cryptopro.ru/support/stunnel/dist/csp50r2/linux-amd64_deb.tgz --output linux-amd64_deb.tgz
          tar -xvf linux-amd64_deb.tgz
          cd linux-amd64_deb
          sudo ./install.sh kc1
        else
          exit 1
        fi

    - name: TestMsspiClient
      shell: bash
      run: |
        go test -run MsspiClient
